{% set name = "pandas-gbq" %}
{% set version = "0.17.2" %}
{% set sha256 = "d6d88090eedfb188ea6275d8812ff0cb876754e168760bd446b8d0fe242eae52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - pip

  run:
    - python >=3.7.0
    - setuptools
    - db-dtypes >=0.3.1,<2.0.0dev
    - numpy >=1.16.6
    - pandas >=0.24.2
    - pyarrow >=3.0.0,<7.0dev
    - pydata-google-auth
    - google-api-core >=1.21.0
    - google-auth >=1.18.0
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.27.2,<4.0.0dev
    - google-cloud-bigquery-storage >=1.1.0,<3.0.0dev
  run_constrained:
    - tqdm >=4.23.0

test:
  requires:
    - python
    - pip
  imports:
    - pandas_gbq
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-bigquery-pandas
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: https://googleapis.dev/python/pandas-gbq/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-pandas

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - tswast
