{% set name = "pandas-gbq" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandas_gbq-{{ version }}.tar.gz
  sha256: e68cea81b55761e11bc154ec2ac8c9f55d8605bd51039f9af45069236e5aa401

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - db-dtypes >=1.0.4,<2.0.0
    - numpy >=1.18.1
    - pandas >=1.1.4
    - pyarrow >=4.0.0
    - pydata-google-auth >=1.5.0
    - google-api-core >=2.10.2,<3.0.0dev
    - google-auth >=2.13.0
    - google-auth-oauthlib >=0.7.0
    - google-cloud-bigquery-core >=3.4.2,<4.0.0dev
    - google-cloud-bigquery-storage >=2.16.2,<3.0.0dev
    - packaging >=22.0.0
  run_constrained:
    - tqdm >=4.23.0

test:
  imports:
    - pandas_gbq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-bigquery-pandas
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: https://googleapis.dev/python/pandas-gbq/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-pandas

extra:
  recipe-maintainers:
    - chalmerlowe
    - jreback
    - leahecole
    - parthea
    - tswast
