{% set name = "pandas-gbq" %}
{% set version = "0.17.9" %}
{% set sha256 = "066eacb9c3b18dec7bccd0a0ea67a3bdd79519255be4e59231e5d323ac984fe8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - pip

  run:
    - python >=3.7.0
    - setuptools
    - db-dtypes >=0.3.1,<2.0.0dev
    - numpy >=1.16.6
    - pandas >=0.24.2
    - pyarrow >=3.0.0,<10.0dev
    - pydata-google-auth
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.27.2,<4.0.0dev,!=2.4.*
    - google-cloud-bigquery-storage >=1.1.0,<3.0.0dev
  run_constrained:
    - tqdm >=4.23.0

test:
  requires:
    - python
    - pip
  imports:
    - pandas_gbq
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-bigquery-pandas
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: https://googleapis.dev/python/pandas-gbq/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-pandas

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - tswast
