{% set name = "pandas-gbq" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas-gbq-{{ version }}.tar.gz
  sha256: f9c137430d34059f380af6c37781334d0be0a16021a8bdbf2836687e50ab63af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools
    - db-dtypes >=1.0.4,<2.0.0
    - numpy >=1.16.6
    - pandas >=1.1.4
    - pyarrow >=3.0.0
    - pydata-google-auth >=1.5.0
    - google-api-core >=2.10.2,<3.0.0dev
    - google-auth >=2.13.0
    - google-auth-oauthlib >=0.7.0
    - google-cloud-bigquery-core >=3.3.5,<4.0.0dev,!=2.4.*
    - google-cloud-bigquery-storage >=2.16.2,<3.0.0dev
    - packaging >=20.0.0
  run_constrained:
    - tqdm >=4.23.0

test:
  imports:
    - pandas_gbq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-pandas
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: https://googleapis.dev/python/pandas-gbq/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-pandas

extra:
  recipe-maintainers:
    - chalmerlowe
    - jreback
    - leahecole
    - parthea
    - tswast
